DNA=input("Enter your DNA sequence=")
t=print("")
a=DNA.replace("a",str(t))
a=a.replace("t","a")
a=a.replace(str(t),"t")
g=print("")
a=a.replace("g",str(g))
a=a.replace("c","g")
a=a.replace(str(g),"c")
print('\n', "DNA Sequence",DNA)
print('\n', "Complimentary sequence in Lower Case=",a.lower())
print('\n', "Complimentary sequence in Upper Case=",a.upper())
